### ISSUE TITLE
PWS Weather data source

### ISSUE THREAD

**Issue by philgood** [HomeKidd/ESP8266-HomeKit-WeatherUnderGround-PWS#2]
Thanks for making this project come alive, I will start to get the parts and build this project. But fully understand that its still under development.

Do you think it would be difficult to incorporate the ability to upload the weather data to [PWS Weather](https://www.pwsweather.com) as well? I have other apps that use PWS weather and would be good to upload local weather data to that source.

Cheers!

**Comment by HomeKidd** [comment]
Hi!

I don't want to add PWS Weather support because as i've take a look at the map, it has much less active weather stations than WU. Just near me i have 6-7 WU weather stations and theres no PWS Weather's station within 50km range. 
WunderGround is a widely available service, with great  documentation (like upload API) and even Apple's weather app uses WU station's data too.

Also please take a look at the [readme](https://github.com/HomeKidd/ESP8266-HomeKit-WeatherUnderGround-PWS) because a new version of the PCB/code coming out soon with support for Windspeed/Gust/Directions too 😄
